// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChUiOVanVDALrXCTgMs4Zegc_Ks2iWpk4',
    appId: '1:897095370915:web:b5014eeb2d8d50b6399716',
    messagingSenderId: '897095370915',
    projectId: 'grocery-d25ed',
    authDomain: 'grocery-d25ed.firebaseapp.com',
    storageBucket: 'grocery-d25ed.appspot.com',
    measurementId: 'G-871D89QZ07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGv2_6rnXW3ZKTBSj_mlnk4JK0dNaY_s',
    appId: '1:897095370915:android:f6d6e7152f4caa7a399716',
    messagingSenderId: '897095370915',
    projectId: 'grocery-d25ed',
    storageBucket: 'grocery-d25ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9a0fMSLsT95v8kALE8f8nbJUa2OJcNdE',
    appId: '1:897095370915:ios:696c234559185694399716',
    messagingSenderId: '897095370915',
    projectId: 'grocery-d25ed',
    storageBucket: 'grocery-d25ed.appspot.com',
    androidClientId: '897095370915-pupec2gpbsrl65bn0kensls9jengb90b.apps.googleusercontent.com',
    iosClientId: '897095370915-m5tjncpjperackb9s3piasvmmk05hfht.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9a0fMSLsT95v8kALE8f8nbJUa2OJcNdE',
    appId: '1:897095370915:ios:696c234559185694399716',
    messagingSenderId: '897095370915',
    projectId: 'grocery-d25ed',
    storageBucket: 'grocery-d25ed.appspot.com',
    androidClientId: '897095370915-pupec2gpbsrl65bn0kensls9jengb90b.apps.googleusercontent.com',
    iosClientId: '897095370915-m5tjncpjperackb9s3piasvmmk05hfht.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChUiOVanVDALrXCTgMs4Zegc_Ks2iWpk4',
    appId: '1:897095370915:web:eaed1db1b4a30d06399716',
    messagingSenderId: '897095370915',
    projectId: 'grocery-d25ed',
    authDomain: 'grocery-d25ed.firebaseapp.com',
    storageBucket: 'grocery-d25ed.appspot.com',
    measurementId: 'G-KKE5YV164E',
  );

}